# Generated by Django 4.2.2 on 2023-07-11 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheBlogsApp', '0003_alter_blogpost_author_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='creationDate',
            new_name='creation_date',
        ),
    ]
